mysite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post_category/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<slug:post>/<int:year>/<int:month>/<int:day>', views.post_detail, name='post_detail'),
    path('categories/<slug:tag_slug>/', views.by_categories, name='by_categories'),
    path('all/', views.all_categories, name='all_categories'),
    path('feed/', LatestPostFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),

]

mysite/home_page/urls.py
from django.urls import path
from . import views

app_name = 'home_page'
urlpatterns = [
    path('', views.home_page_view, name='home_page_view'),
    path('about_us/', views.about_us_page_view, name='about_us_page_view'),
    path('disclaimer/',views.disclaimers_view, name='disclaimers_view'),
    path('contact/', views.contact, name='contact'),
    path('attributes/', views.attributes, name='attributes')

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from home_page.sitemaps import PostSitemap
from django.views.generic.base import TemplateView
import environ

env = environ.Env()
environ.Env.read_env()

sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path(env('SECRET_ADMIN_URL') + '/admin/', admin.site.urls),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('payments/', include('payments.urls', namespace='payments')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('store/', include('store.urls', namespace='store')),
    path('insightsTwo/',include('insightsTwo.urls', namespace='insightsTwo')),
    path('', include('home_page.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name="django.contrib.sitemaps.views.sitemap"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

]

mysite/home_page/models.py
from django.db import models

# Create your models here.

mysite/home_page/forms.py
from django import forms

# Create your forms here.

class ContactForm(forms.Form):
    name = forms.CharField(max_length = 50, required=True)
    email_address = forms.EmailField(max_length=150, required=True)
    message = forms.CharField(widget = forms.Textarea, max_length=2000, required=True)

    class Meta:
        fields = ['name', 'email', 'message']

mysite/home_page/views.py
from django.shortcuts import render, redirect
from blog.models import Post
from store.models import Product
from .forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
import environ
import os

# Create your views here.
def home_page_view(request):
    last_three_post = Post.published.filter().order_by('-publish')[:3]
    product =  Product.objects.filter().order_by('id')[:1]
    
    return render(request, 'home_page/index.html', {'last_three_post': last_three_post, 'product': product})

def about_us_page_view(request):
    return render(request, 'home_page/about_us.html')

def disclaimers_view(request):
    return render(request, 'home_page/disclaimer.html')

def contact(request):
    product =  Product.objects.filter().order_by('id')[:1]
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = 'Seville Report Inquiry'
            body = {
                'name': form.cleaned_data['name'],
                'email': form.cleaned_data['email_address'],
                'message': form.cleaned_data['message'],
            }
            message = '\n'.join(body.values())
            from_email_address=os.environ.get('EMAIL_HOST_USER')
            try:
                send_mail(subject, message, from_email_address, [from_email_address])
                print('from_email_address', from_email_address)
                print('subject:', subject, 'message:', message )
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('home_page:home_page_view')

    form = ContactForm()
    return render(request, 'home_page/contact.html', {'form': form})

def attributes(request):
    return render(request, 'home_page/attributes.html')

mysite/templates/home_page/about_us.html
{% extends 'layout.html' %}

{% block title %}
    About Us
{% endblock %}

{% block main %}
    <section class="about_us_section">
            <h1 class="section_title_blue">About Us</h1>
        <div class="container about_bx">
            <div class="about_inner_bx">
                <h2 class="about_bx_title">We're Making Good Investing Easy</h2>
                <p class="about_bx_desc">The Seville Report is a digital investment newsletter for 
                    all investors. The newsletter provides well thought out investment 
                    ideas, so that investors can avoid the noise of Wall Street and make investment
                    decisions that are best for them.
                </p>
            </div>
            <div class="about_inner_bx_two">
                <ul class="about_ul">
                    <li class="about_li">Educate
                        <span class="hidden_text">We want to <strong>educate</strong> our readers and remove the mystery that surrounds the stock market and good investing.</span>
                    </li>
                    <li class="about_li">Empower
                        <span class="hidden_text">We want to <strong>empower</strong> our readers to make investment decisions that best fit them and their financial plans.</span>
                    </li>
                    <li class="about_li">Inspire
                        <span class="hidden_text">We want to <strong>inspire</strong> our readers to think and invest long-term to reach their financial.</span>
                    </li>
                    <li class="about_li">Inform
                        <span class="hidden_text">We strive to keep our readers <strong>informed</strong> with the information that's moving the markets.</span>
                    </li>
                </ul>
            </div>
        </div>
    </section>
{% endblock %}

mysite/templates/home_page/attributes.html
{% extends 'layout.html' %}

{% block title %}
    About Us
{% endblock %}

{% block main %}
<section class="attribute_section">
    <h1 class="section_title_blue">Attributes</h1>

    <div class="container attributes_container">
        <h2 class="all_posts_slug attr_bx_title">Images</h2>
        
        <ul class="image_attributes">
            <li class="img_attr">
                <a href="https://www.pexels.com/@ivan-samkov/" target="_blank">Consumer Disc Image</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@padrinan/" target="_blank">Communication Services</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@conojeghuo/" target="_blank">Consumer Staples</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@narcisa-aciko-541222/" target="_blank">Energy</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@karolina-grabowska/" target="_blank">Finance</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@karolina-grabowska/" target="_blank">Healthcare</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@samuel-wolfl-628277/" target="_blank">Industrial</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@luis-gomes-166706/" target="_blank">Information Technology</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@chokniti-khongchum-1197604/" target="_blank">Materials</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@jessica-bryant-592135/" target="_blank">Real Estate</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@annette-bauer-358235/" target="_blank">Utilities</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@anntarazevich/" target="_blank">S&P 500</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@nivdex/" target="_blank">Aerospace and Defense</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@brett-sayles/" target="_blank">Airlines</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@hebertsantos/" target="_blank">Autoparts</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@mikebirdy/" target="_blank">Automobiles</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@expect-best-79873/" target="_blank">Banking</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@thatguycraig000/" target="_blank">Beverages</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@chokniti-khongchum-1197604/" target="_blank">Biotechnology</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@rezwan/" target="_blank">Construction Products</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@rdne/" target="_blank">Capital Markets</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@loic-manegarium/" target="_blank">Chemicals</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@tim-samuel/" target="_blank">Commercial Services and Supplies</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@brett-sayles/" target="_blank">Communication Equipment</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@jiyoung-kim-2937986/" target="_blank">Construction & Engineering</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@life-of-pix/" target="_blank">Construction Materials</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@goumbik/" target="_blank">Consumer Finance</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@cottonbro/" target="_blank">Container and Packaging</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@joenibraw/" target="_blank">Diversfied Telecom</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@distelapparath/" target="_blank">Diversfied Utilities</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@timmossholder/" target="_blank">Electrical Equipment</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@muffin/" target="_blank">Electrical Equipment and Instrument Components</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@onics-energy-357829293/" target="_blank">Energy Equipment Services</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@rahulp9800/" target="_blank">Entertainment</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@davidmcbee/" target="_blank">Equity Real Estate</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@foodie-factor-162291/" target="_blank">Food Products</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@carlo-martin-alcordo-1279322/" target="_blank">Food Staples</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@souvenirpixels/" target="_blank">Freight and Logistics</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@mart-production/" target="_blank">Healthcare Equipment</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@alexandros-chatzidimos-2033032/" target="_blank">Healthcare Services</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@chanwalrus/" target="_blank">Hotel, Restaurant, and Leisure</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@curtis-adams-1694007/" target="_blank">Household Durables</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@shvetsa/" target="_blank">Household Products</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@kateryna-babaieva-1423213/" target="_blank">Industrial Conglomerate</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@goumbik/" target="_blank">Information Technology Services</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@kindelmedia/" target="_blank">Insurance</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@aloksharma/" target="_blank">Interactive Meda</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@cottonbro/" target="_blank">Internet Retail</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@polina-tankilevitch/" target="_blank">Life Science Tools and Services</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@rezwan/" target="_blank">Machinery</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@ninosouza/" target="_blank">Media</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@chetanvlad/" target="_blank">Metals and Mining</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@demiansmit/" target="_blank">Multiline Retail</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@jan-rune-smenes-reite-221584/" target="_blank">Oil, Gas, and Consumable Fuels</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@suzyhazelwood/" target="_blank">Pharmaceuticals</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@rdne/" target="_blank">Professional Services</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@didsss/" target="_blank">Regulated Electric</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@michael-pointner-134459625/" target="_blank">Regulated Gas</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@brett-sayles/" target="_blank">Road and Rail</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@waterhouse/" target="_blank">Semiconductor and Semiconductor Equipment</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@tima-miroshnichenko/" target="_blank">Software</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@max-fischer/" target="_blank">Specialty Retail</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@digitalbuggu/" target="_blank">Textiles, Apparel, and Luxury Goods</a>
            </li>
            <li class="img_attr">
                <a href="https://www.pexels.com/@tiger-lily/" target="_blank">Trading Companies and Distributors</a>
            </li>
        </ul>
    </div>
</section>
{% endblock %}

mysite/templates/home_page/contact.html
{% extends "layout.html" %}
{% load static %}


{% block title %}
    Contact
{% endblock %}

{% block main %}
<section class="contact_section">
        <h1 class="section_title_blue">Contact Us</h1>

    <div class="container email_container">
        <form class="email_form" method="post">
            {% csrf_token %}
            <p>
                Please provide your name, email address and a messeage below 
            </p>
            <div class="form_name">
                <h4 class="contact_name">Name:</h4>
                <div class="name_input"> {{ form.name }}</div>
            </div>
            <div class="form_email">
                <h4 class="contact_email">Email:</h4>
                <div class="email_input"> {{ form.email_address }}</div>
            </div>
            <div class="form_message">
                <h4 class="contact_message">Message:</h4>
                <div class="message_input"> {{ form.message }}</div>
            </div>
    
            <button class="input_submit" type="submit">Submit</button>
        </form>
    </div>
</section>
{% endblock %}

mysite/templates/home_page/index.html
{% extends "layout.html" %}
{% load static %}


{% block title %}
    Home
{% endblock %}

{% block main %}

<main class="home_section" id="bg">
        <div class="container home_container">
            <div class="home_box">
                <div class="inner_home_box">
                    <h1 class="home_title">Where are your investments taking you?</h1>
                    <p class="home_paragraph">The Seville Report Newsletter helps investors reach new<br>heights by spotlighting long-term investment ideas.</p>
                    <a href="{% url 'store:product_detail' 1 'the-seville-report-investment-newsletter-sept-2022' %}" aria-label="to current newsletter" tabindex="7"><button class="btn_dark">newsletter</button></a> 
                </div>
                <div class="social_media_block">
                    <a href="https://www.facebook.com/SevilleReport" class="social_block_link" target="_blank"><i class="fab fa-facebook-square"></i></a>
                    <a href="https://www.instagram.com/the_seville_report/" class="social_block_link" target="_blank"><i class="fab fa-instagram-square"></i></a>
                    <a href="https://twitter.com/SevilleReport" class="social_block_link" target="_blank"><i class="fab fa-twitter-square"></i></a>
                </div>
            </div> 
        </div> 
    </main>
<hr>


<aside class="recent_recommendations">
    <h1 class="section_title_blue">Recent Recommendation</h1>
    <div class="container recom_container">
        <div class="recommend_items">
            <div class="rec_icons"><i class="fa-solid fa-file-invoice-dollar"></i></i></div>
            <div class="rec_desc">$AMKR</div>
        </div>
        <div class="recommend_items">
            <div class="rec_icons"><i class="fa-regular fa-building"></i></div>
            <div class="rec_desc">Amkor Technology, Inc.</div>
        </div>
        <div class="recommend_items">
            <div class="rec_icons"><i class="fa-solid fa-money-bill-trend-up"></i></div>
            <div class="rec_desc">+35%</div>
        </div>
        <div class="recommend_items">
            <img class="recom_photo" src="media/products/2022/09/24/SR_March_22_Image.001.jpeg" alt="image of March 2022 mewsletter cover ">
            <h3 class="recom_date">Recommended<br>March 2022</h3>
        </div>
    </div>
    <div class="newsletter_discover">
        <p class="discover">
            <a href="#" class="discover_link" target="_blank">
                <span class="highlights">Discover</span>
            </a> what makes The Seville Report different.
        </p>
    </div>
</aside>
<hr>


<section class="newsletter_section"  id="bg_two">
        <h1 class="section_title_white">The Seville Report Newsletter</h1>
    <div class="container news_container">
        <div class="news_left">
            <div class="newsletter_description">
                <h2 class="news_desc">Our quarterly newsletter provides the information that investors need to know 
                    to build wealth. We discuss traditional investments, alternative investments, and investment 
                    education. The Seville Report has you covered.
                </h2>
            </div>
            <div class="description_two">
                <p class="curr_desc">This quarter's newsletter features a researched investment idea. In addition, we discuss if an Index Universal Life Insurance plicy can be an infinite bank in retirement and why gas prices have been so high in 2022.</p>
            </div>
            
            <div class="news_block" id="newsletter_news_block">
                <a href="https://www.facebook.com/SevilleReport" class="social_block_link" target="_blank"><i class="fab fa-facebook-square"></i></a>
                <a href="https://www.instagram.com/the_seville_report/" class="social_block_link" target="_blank"><i class="fab fa-instagram-square"></i></a>
                <a href="https://twitter.com/SevilleReport" class="social_block_link" target="_blank"><i class="fab fa-twitter-square"></i></a>
            </div>
        </div>
        <div class="news_right">
            <div class="newsletter_image">
                <img src="{% static 'img/SR_Sept_22.jpeg' %}" alt="picture of newsletter cover" class="curr_newsletter">

                {% comment %}
                <img src="{{ product.image.url }}" alt="picture of current newsletter cover" class="curr_newsletter">
                {% endcomment %}

                <a href="{% url 'store:product_detail' 1 'the-seville-report-investment-newsletter-sept-2022' %}"><button class="btn_light">Purchase Now</button></a>
            </div> 
        </div>
    </div> 
</section>
<hr>

<section class="blog_section">
    <h1 class="section_title_blue">The SR Blog</h1>
    <div class="container card_container">
        {% for post in last_three_post %}
        <div class="card">
            <a href="{{ post.get_absolute_url }}">
                <div class="card_image"><img class="blog_card_image" src="{{ post.post_header_image.url }}" alt="blog cover image"></div>
                <div class="card_text">
                    <div class="date">{{ post.publish|date:"M d, Y " }}<span>|{{ post.publish|date:" f A" }}</span></div>
                    <h2>{{ post.title|title }}</h2>
                    <p>{{ post.post_description }}</p>
                </div>
                <div class="card_stats">
                    <div class="stat">
                        <div class="value">{{ post.get_read_time }}<sup>m</sup></div>
                        <div class="type">Read</div>
                    </div>
                    <div class="stat border">
                        <div class="value">{{ post.author.first_name|title }} {{ post.author.last_name|title}}</div>
                        <div class="type">@SevilleReport</div>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
    <div class="home_page_blog_button">
        <button class="btn_dark"><a href="{% url 'blog:post_list' %}">More Posts</a></button>
    </div>
        <div class="container blue_social_media_block">
            <a href="https://www.facebook.com/SevilleReport" class="blue_social_block_link" target="_blank"><i class="fab fa-facebook-square"></i></a>
            <a href="https://www.instagram.com/the_seville_report/" class="blue_social_block_link" target="_blank"><i class="fab fa-instagram-square"></i></a>
            <a href="https://twitter.com/SevilleReport" class="blue_social_block_link" target="_blank"><i class="fab fa-twitter-square"></i></a>
        </div>
</section>
{% endblock %}