mysite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post_category/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<slug:post>/<int:year>/<int:month>/<int:day>', views.post_detail, name='post_detail'),
    path('categories/<slug:tag_slug>/', views.by_categories, name='by_categories'),
    path('all/', views.all_categories, name='all_categories'),
    path('feed/', LatestPostFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from home_page.sitemaps import PostSitemap
from django.views.generic.base import TemplateView
import environ

env = environ.Env()
environ.Env.read_env()

sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path(env('SECRET_ADMIN_URL') + '/admin/', admin.site.urls),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('payments/', include('payments.urls', namespace='payments')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('store/', include('store.urls', namespace='store')),
    path('insightsTwo/',include('insightsTwo.urls', namespace='insightsTwo')),
    path('', include('home_page.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name="django.contrib.sitemaps.views.sitemap"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager

from django.utils.html import strip_tags




# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

        
class Post(models.Model):
    STATUS_CHOICE = (
        ('draft', 'Draft'),
        ('published', 'Published'),
        ('pending review', 'Pending Review'),
        ('scheduled', 'Scheduled'),
        ('trash', 'Trash')
        )
    
    title = models.CharField(max_length=250)
    subtitle = models.CharField(max_length=250, null=True, default=" ", blank=True)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    overview = RichTextField(blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    post_description = models.CharField(max_length=200)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=25, choices = STATUS_CHOICE, default='draft')
    post_header_image = models.ImageField(upload_to='blog_images/', default='default.jpeg')
    post_images = RichTextUploadingField(blank=True)
    image_url = models.CharField(max_length=500, default=None, null=True, blank=True)
    # hash_tags = TaggableManager()
    post_categories = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.body

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug, self.publish.year, self.publish.month, self.publish.day])
 
    def get_word_count(self, body):
        letters = 0
        words = 1
        sentence = 0
        for i in range(len(body)):
            if body[i].isalpha():
                letters += 1
            elif body[i] == " ":
                words += 1
            elif body[i] == '.' or body[i] == '?' or body[i] == '!':
                sentence += 1
        return words

    def get_read_time(self):
        word_count = self.get_word_count(self.body)
        time_taken = word_count / 200
        whole_number = int(time_taken)
        decimal_nums = (time_taken % 1) * .60
        if decimal_nums > .30:
            time_to_read = whole_number + 1
        else:
            time_to_read = whole_number
        return time_to_read


    objects = models.Manager()
    published = PublishedManager()
 

mysite/blog/forms.py
from django import forms


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class SearchForm(forms.Form):
    query = forms.CharField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['query'].label = ''
        self.fields['query'].widget.attrs.update(
            {'placeholder': 'Search'}
        )

mysite/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, SearchForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from collections import Counter
from django.http import HttpResponse
from django.views import View
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core.cache import cache



# Create your views here.
def post_list(request,tag_slug=None):
    object_list = Post.published.all()

    post_category = None

    if tag_slug:
        post_category = get_object_or_404(Tag, slug=tag_slug)
      
    object_list.filter(post_categories__in=[post_category])

    paginator = Paginator(object_list, 10)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)

    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
   
    return render(request, 'blog/post/blogs.html', 
    {'page': page, 
    'posts': posts, 
    'post_category': post_category })


def post_detail(request, year, month, day, post):

    the_post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    
    if cache.get(the_post):
        post = cache.get(the_post)
    else:
        try:
            post = the_post
            cache.set(the_post, post)
        except Exception as e:
            return redirect('/')

    post_tags_ids = post.post_categories.values_list('id', flat=True)
    similar_posts = Post.published.filter(post_categories__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('post_categories')).order_by('-same_tags', '-publish')[:4]
    
    return render(request, 'blog/post/detail.html', {'post':post, 'similar_posts':similar_posts})


def by_categories(request, tag_slug):
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)

    posts = Post.published.filter(post_categories=tag).order_by('-publish')
    similar_posts = posts.annotate(same_tags=Count('post_categories')).order_by('-same_tags', '-publish')

    paginator = Paginator(posts, 10)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)

    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    
    return render(request, 'blog/post/categories.html',
     {
        'tag': tag, 
        'similar_posts': similar_posts, 
        'page': page, 
        'posts': posts, 
    })

def all_categories(request):
    all_cat_names = list()
    all_cat_slugs = list()

    tags = Tag.objects.all()
    for tag in tags.values():
        if tag['name'] not in all_cat_names:
            all_cat_names.append(tag['name'])
            all_cat_slugs.append(tag['slug'])


    all_cats = {}
    for i in all_cat_names:
        for cat in tags.values():
            if i == cat['name']:
                all_cats[i] = cat['slug']


    return render(request, 'blog/post/all.html', {'all_cats': all_cats})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                search=search_vector, 
                rank=SearchRank(search_vector, search_query)).filter(search=search_query).order_by('-rank')
    
    all_cat_names = list()
    all_cat_slugs = list()

    tags = Tag.objects.all()
    for tag in tags.values():
        if tag['name'] not in all_cat_names:
            all_cat_names.append(tag['name'])
            all_cat_slugs.append(tag['slug'])


    all_cats = {}
    for i in all_cat_names:
        for cat in tags.values():
            if i == cat['name']:
                all_cats[i] = cat['slug']
    
    return render(request, 'blog/post/search.html', {'form': form, 'query': query, 'results': results, 'all_cats': all_cats})

mysite/templates/blog/post/all.html
{% extends "layout.html" %}
{% load blog_tags %}

{% block title %}All Post Categories{% endblock %}

{% block main %}
<section class="blogs_by_tag_section" >
        <h1 class="section_title_blue">All Post Categories</h1>
        <h4 class="all_posts_slug post_related_to">Find a Post by its Category</h4>
    <div class="container all_cats_section">
        {% for k, v in all_cats.items %}
        <button class="cat_button"><a href="{% url 'blog:by_categories' v %}">{{ k }}</a></button>
        {% endfor %}
    </div>
</section>

{% endblock %}

mysite/templates/blog/post/blogs.html
{% extends "layout.html" %}
{% load blog_tags %}

{% block title %}The Seville Report Blog{% endblock %}

{% block main %}
<aside class="blog_page_header">
    <h1 class="section_title_blue">All Posts</h1>
    <h4 class="container all_posts_slug">Our thoughts on the events shaping the market</h4>

    <div class="container blog_categories">
            {% total_categories as tc %}
            {% for key, value in tc.items %}
        <h4 class="categories">
            <a href="{% url 'blog:by_categories' value %}">{{ key|title }}</a>
        </h4>
            {% endfor %}
        <h4><a class="more_categories" href="{% url 'blog:all_categories' %}">More</a></h4>
        <a href="{% url 'blog:post_search' %}"><i class="fa-solid fa-magnifying-glass"></i></a>
        <a href="{% url 'blog:post_feed' %}"><i class="fa-solid fa-square-rss"></i></a>
    </div>
</aside> 

<section class="blog_page_body">
    <div class="container blog_container">
        {% for post in posts %}
        <div class="post_section">
            <div class="pic_title_snip">
                <a href="{{ post.get_absolute_url }}">
                    <img src='{{ post.post_header_image.url }}' alt="blog post image" class="post_image">
                </a>
                <div class="post_desc">
                    <a href="{{ post.get_absolute_url }}">
                        <h1 class="post_title"><a href="{{ post.get_absolute_url }}">{{ post.title|title }}</h1>
                        <p class="post_snippet">{{ post.post_description|truncatewords:25 }}</p>
                        <p id="post_snippet_mobile_view">{{ post.post_description|truncatewords:10 }}</p>
    
    
                        <div class="auth_and_opinion">
                            <h3 class="author">{{ post.author.first_name|title }} {{ post.author.last_name|title}}</h3>
                            <h3 class="opinion">Opinion</h3>
                        </div>
                        <div class="pubdate_readtime">
                            <h3 class="publish_date">{{ post.publish|date:"M d, Y " }}<span>|{{ post.publish|date:" f A" }}</span></h3>
                            <h3 class="read_time">{{ post.get_read_time }} Minutes</h3>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
        {% include '../pagination.html' with page=posts %}
    </div>
    
</section>


{% endblock %}

mysite/templates/blog/post/categories.html
{% extends "layout.html" %}
{% load blog_tags %}

{% block title %}Post Related To {{ tag }}{% endblock %}

{% block main %}
<aside class="blog_page_header">
    <h1 class="section_title_blue">{{ tag }}</h1>
    <h4 class="all_posts_slug">Post Related to {{ tag  }}</h4>
    <div class="container blog_categories">
        {% total_categories as tc %}
        {% for key, value in tc.items %}
    <h4 class="categories">
        <a href="{% url 'blog:by_categories' value %}">{{ key|title }}</a>
    </h4>
        {% endfor %}
    <h4 class="categories"><a href="{% url 'blog:all_categories' %}">More</a></h4>
    <a href="{% url 'blog:post_search' %}"><i class="fa-solid fa-magnifying-glass"></i></a>
    <a href="{% url 'blog:post_feed' %}"><i class="fa-solid fa-square-rss"></i></a>
</div>
</aside> 
<section class="blog_page_body">
    <div class="container cats_container">
        {% for post in similar_posts %}
        <div class="post_section">
            <div class="pic_title_snip">
                <a href="{{ post.get_absolute_url }}">
                    <img src='{{ post.post_header_image.url }}' alt="blog post image" class="post_image">
                </a>
                <div class="post_desc">
                    <a href="{{ post.get_absolute_url }}">
    
                        <h1 class="post_title"><a href="{{ post.get_absolute_url }}">{{ post.title|title }}</h1>
                        <p class="post_snippet">{{ post.post_description|truncatewords:25 }}</p>
                        <p id="post_snippet_mobile_view">{{ post.post_description|truncatewords:10 }}</p>
    
    
                        <div class="auth_and_opinion">
                            <h3 class="author">{{ post.author.first_name|title }} {{ post.author.last_name|title}}</h3>
                            <h3 class="opinion">Opinion</h3>
                        </div>
                        <div class="pubdate_readtime">
                            <h3 class="publish_date">{{ post.publish|date:"M d, Y " }}<span>|{{ post.publish|date:" f A" }}</span></h3>
                            <h3 class="read_time">{{ post.get_read_time }} Minutes</h3>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
        {% include '../pagination.html' with page=posts %}
    </div>
</section>
{% endblock %}

mysite/templates/blog/post/detail.html
{% extends "layout.html" %}
{% load static %}
{% block title %}{{ post.title }}{% endblock %}


{% block main %}
<section class="blog_area_section">
    <div class="container blog_post_container">
      <aside class="prev_blog_section">
        <h1 class="section_title_blue">Related Post</h1>
        {% for post in similar_posts %}
        <div class="post_img_and_title">
          <a href="{{ post.get_absolute_url }}"><img class="prev_post_img" src="{{ post.post_header_image.url }}" alt=""></a>
          <h4 class="prev_post_title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        </div>
          {% empty %}
          There are no similar posts yet.
          {% endfor %}
      </aside>

      <article class="blog_area">
        <div class="blog_title_slug_area">
          <h1 class="the_blog_title">{{ post.title|title }}</h1>
          <h2 class="blog_subtitle">{{ post.subtitle|title }}</h2>
        </div>
  
        <div class="auth_pub_read_area">
            <div class="blog_author">By {{ post.author.first_name|title }} {{ post.author.last_name|title}}</div>
            <div class="pub_date_read_time">
              <div class="blog_pub_date">{{ post.publish|date:"M d, Y " }}<span>|{{ post.publish|date:" f A" }}</span></div>
              <div class="blog_read_time">{{ post.get_read_time}} Minutes</div>
            </div>
        </div>
        <img class="blog_main_img" src="{{ post.post_header_image.url }}" alt="main blog image">
        <div class="blog_overview">{{ post.overview|safe }}</div>
        <hr class="blog_hr">
        <article class="blog_text">{{ post.body|safe }}</article>
        <a href="{% url 'store:product_list' %}"><img class="newsletter_promotion" src="{% static 'img/SR_Adv.png' %}" alt=""></a>
      </article>

      <div class="social_sidebar">
        <a href="https://www.facebook.com/SevilleReport" class="blog_icon_link" target="_blank"><i class="fab fa-facebook-square"></i></a>
        <a href="https://www.instagram.com/the_seville_report/" class="blog_icon_link" target="_blank"><i class="fab fa-instagram-square"></i></a>
        <a href="https://twitter.com/SevilleReport" class="blog_icon_link" target="_blank"><i class="fab fa-twitter-square"></i></a>
        <a href="mailto:?subject={{ post.title|title }}&body=Check%20out%20this%20post%20from%20The%20Seville%20Report%20|%20sevillereport{{ post.get_absolute_url }}" class="blog_icon_link" target="_blank"><i class="fa-regular fa-envelope"></i></a>
        <a href="https://www.linkedin.com/" class="blog_icon_link" target="_blank"><i class="fa-brands fa-linkedin"></i></a>
        <a href="https://www.reddit.com/" class="blog_icon_link" target="_blank"><i class="fa-brands fa-square-reddit"></i></a>
        <a href="https://www.tumblr.com/" class="blog_icon_link" target="_blank"><i class="fa-brands fa-square-tumblr"></i></a>
        <a href="https://telegram.org/" class="blog_icon_link" target="_blank"><i class="fa-brands fa-telegram"></i></a>
      </div>
  
      <a class="blog_sidebar" href="{% url 'store:product_detail' 1 'the-seville-report-investment-newsletter-sept-2022' %}">
        <img src="{% static 'img/theAd.jpeg' %}" alt="">
      </a>

    </div>
  
  
    

</section>

{% endblock %}

mysite/templates/blog/post/search.html
{% extends 'layout.html' %}
{% load blog_tags %}
{% block title %}Search{% endblock %}

{% block main %}
{% if query %}
<section class="search_section">
    <main class="container search_container">
        <h1 class="section_title_blue">Post Containing "{{ query }}"</h1>
        <h3 class="search_result">{% with results.count as total_results %} Found {{ total_results }} 
            Result {{ total_results|pluralize }}{% endwith %}
        </h3>
        {% for post in results %}
            <h4 class="search_result_blog_title"><a href="{{ post.get_absolute_url}}">{{ post.title }}</a></h4>
               {{ post.body|safe|truncatewords_html:50 }}
                {% empty %}
            <p>There are no results for your query</p>
            {% endfor %}
            <p class="search_again"><a href="{% url 'blog:post_search' %}">Search Again</a></p>
    </main>
            {% else %}
    <main class="container search_container">
        <h1 class="search_page_title">Search for Posts</h1>
        <form method="get" action="">{{ form.as_p }}
            <input type="submit" value="Search">
        </form>
        <div class="container all_cats_section">
            {% for k, v in all_cats.items %}
            <button class="cat_button"><a href="{% url 'blog:by_categories' v %}">{{ k }}</a></button>
            {% endfor %}
        </div>
        
    </main>
    {% endif %}
    {% endblock %}

       
</section>