mysite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post_category/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<slug:post>/<int:year>/<int:month>/<int:day>', views.post_detail, name='post_detail'),
    path('categories/<slug:tag_slug>/', views.by_categories, name='by_categories'),
    path('all/', views.all_categories, name='all_categories'),
    path('feed/', LatestPostFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from home_page.sitemaps import PostSitemap
from django.views.generic.base import TemplateView
import environ

env = environ.Env()
environ.Env.read_env()

sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path(env('SECRET_ADMIN_URL') + '/admin/', admin.site.urls),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('payments/', include('payments.urls', namespace='payments')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('store/', include('store.urls', namespace='store')),
    path('insightsTwo/',include('insightsTwo.urls', namespace='insightsTwo')),
    path('', include('home_page.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name="django.contrib.sitemaps.views.sitemap"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/payments/urls.py
from django.urls import URLPattern, path
from . import views

app_name = 'payments'
urlpatterns = [
    path('', views.payment_process, name='process'),
    path('start_order/', views.start_order, name='start_order'),
    path('done/', views.payment_done, name='done'),
    path('canceled/', views.payment_canceled, name='canceled'),
]

mysite/payments/models.py
from django.db import models


# Create your models here.

mysite/payments/forms.py
from django import forms
from orders.models import Order

class CreateOrderForms(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email']

mysite/payments/views.py
import mimetypes
from pyexpat import model
import re
from django.forms import FilePathField
from django.http import FileResponse, StreamingHttpResponse
from django.shortcuts import render, redirect, get_object_or_404
import stripe
from django.conf import settings
from cart.views import cart_detail
from orders.models import Order, OrderItem
from django.urls import reverse
from django.http.response import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView
from payments.forms import CreateOrderForms
from orders.forms import OrderCreateForm
from cart.cart import Cart
from orders.tasks import order_created
import json
from store.models import Product
from django.core.mail import EmailMessage
from django.template.loader import render_to_string



# Create your views here.
@csrf_exempt
def start_order(request):
    cart = Cart(request)
    data = json.loads(request.body)
    total_price = 0
    items = []


    for item in cart: 
        product = item['product']
        total_price += product.price * int(item['quantity'])

        obj = {
            'price_data': {
                'currency': 'usd',
                'product_data': {
                    'name': product.name,
                },
                'unit_amount': int(product.price * 100),
            },
            'quantity': item['quantity']
        }

        items.append(obj)
    
    stripe.api_key = settings.STRIPE_SECRET_KEY
    session = stripe.checkout.Session.create(
        payment_method_types=['card'],
        line_items=items,
        mode='payment',
        success_url='http://localhost:8000/payments/done',
        cancel_url='http://localhost:8000/payments/cancel'
    )

    payment_intent = session.payment_intent
    
    first_name = data['first_name']
    last_name = data['last_name']
    email = data['email']

    order = Order.objects.create(first_name=first_name, last_name=last_name, email=email)
    order.payment_intent = payment_intent
    order.paid_amount = total_price
    order.paid  = True
    order.save()

    for item in cart:
        product = item['product']
        quantity = int(item['quantity'])
        price = product.price * quantity

        item = OrderItem.objects.create(order=order, product=product, price=price, quantity=quantity)
    
    return JsonResponse({'session': session, 'payments': payment_intent})


def payment_process(request):
    pub_key = settings.STRIPE_PUBLISHABLE_KEY 
    return render(request, 'payments/process.html', {'pub_key': pub_key})


def payment_canceled(request):
    cart = Cart(request)

    order = Order.objects.values()
    current_order = order[0]
    first_name = current_order['first_name']
    email = current_order['email']

    products = {}
    for c in cart:
        product = c['product']
        price = c['price']

        products[product] = price

    purchased_products = products

    return render(request, 'payments/canceled.html', {'products': purchased_products, 'name': first_name})

def payment_done(request):
    cart = Cart(request)

    order = Order.objects.values()
    current_order = order[0]
    first_name = current_order['first_name']
    email = current_order['email']

    products = {}
    for c in cart:
        product = c['product']
        price = c['price']

        products[product] = price

    purchased_products = products

    template = render_to_string('payments/email_template.html', {'name': first_name})

    try:
        email = EmailMessage(
            'Thank You!',
            template,
            settings.EMAIL_HOST_USER,
            [email],
        )

        email.fail_silently=False
        email.send()

        cart.clear()
    except Exception as e:
        print(f'Exection {e}')
    finally:
        return render(request, 'payments/done.html', {'products':purchased_products})

mysite/templates/payments/canceled.html
{% extends 'layout.html' %}

{% block title %}Payment Canceled{% endblock %}

{% block main %}
  <section class="payment_issue_section">
    <h1 class="section_title_blue">Your Payment Has Not Been Processed</h1>
        <h4 class="all_posts_slug">There Was a Problem Processing Your Payment.</h4>

    <div class="container payment_issue_container">

      <h2 class="issue_greeting">Hey {{ name }},</h2>
      <h3 class="issue_greeting">Something went wrong.</h3>
      <button class="btn_dark"><a href="{% url 'payments:process' %}"> Let's try again</a></button>
      

        <div class="items_container">
          {% for prod in products %}
          <div class="pay_issue_table">
            <div><img class="pay_issue_image" src="{{ prod.image.url }}" alt=""></div>
            <div class="pay_issue_prod_name">{{ prod.name }}</div>
          </div>
        {% endfor %}
      </div>
      


    </div>
  </section>
{% endblock %}

mysite/templates/payments/done.html
{% extends 'layout.html' %}

{% block title %}
  Payment Successful
{% endblock %}


{% block main %}
<section class="success_section">
  <h1 class="section_title_blue">Your Payment Was Successful</h1>
  <h4 class="all_posts_slug">Thank you for your purchase</h4>
  <div class="container success_container">
    <table class="download_table">
      <thead>
        <tr>
          <th class="table_head">Newsletter</th>
          <th class="table_head">Edition</th>
          <th class="table_head table_head_price">Price</th>
          <th class="table_head">Download</th>
        </tr>
      </thead>
      <tbody>
        {% for prod in products %}
        <tr class="table_row">
          <td class="table_data download_pic"><img id="download_pic" src="{{ prod.image.url }}"></td>
          <td class="table_data table_data_prod_name">{{ prod.name }}</td>
          <td class="table_data">${{prod.price}}</td>
          <td class="table_data table_data_prod_download"><button class="btn_dark"><a href="{{prod.pdf_file.url}}" download>Download</a></button></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</section>

<section class="mobile_success_section">
  <h1 class="section_title_blue">Your Payment Was Successful</h1>
  <h4 class="all_posts_slug">Thank you for your purchase</h4>
  <div class="container mobile_success_container">
      {% for prod in products %}
        <div class="mobile_success_table">
          <picture class="mobile_image">
            <img src="{{ prod.image.url }}" alt="mobile product image" class="mobile_prod_img">
          </picture>
          <div class="mobile_details_container">
            <h2 class="mobile_prod_name">{{ prod.name }}</h2>
            <p class="mobile_prod_price"><strong>${{ prod.price}}</strong></p>
            <button class="btn_dark"><a href="{{prod.pdf_file.url}}" download>Download</a></button>
          </div>
        </div>
      {% endfor %}
  </div> 
</section>
{% endblock %}

mysite/templates/payments/email_template.html
Hey {{ name }}:

Just wanted to thank you for purchasing The Seville Report Investment Newsletter.

We hope this quarter's newsletter adds value to your investment objectives. Please feel free to contact me with an questions, comments, or concerns.

Sincerly,

Paul Black
pblack@sevillereport.com

mysite/templates/payments/process.html
{% extends 'layout.html' %}

{% block main %}
<section class="checkout_section">
  <h1 class="section_title_blue">Checkout</h1>
  <div class="container pre_check_container">
    <div class="payment_form">
      <div class="order_form">
        <div class="order_inputs">
          <label class="form_label" for="first_name">First Name</label>
          <input name="first_name" type="text" class="form_control" id="customer_first_name" placeholder="" required />
        </div>
        <div class="order_inputs">
          <label class="form_label" for="first_name">Last Name</label>
          <input name="last_name" type="text" class="form_control" id="customer_last_name" placeholder="" required />
        </div>
        <div class="order_inputs">
          <label class="form_label" for="first_name">Email Address</label>
          <input name="email" type="text" class="form_control" id="customer_email" placeholder="" required />
        </div>

        <button onclick="buy(event)" class="btn_none">
          <p><input type="submit" value="Place Order"></p>
        </button>
        {% csrf_token %}
        <div class="hidden" id="errors"></div>
      </div>
    </div>

    <div class="order_info">
      <h3>Your Order</h3>
      <ul>
        {% for item in cart %}
        <li>
          {{ item.quantity }} x {{ item.product.name }} | <span>${{ item.total_price }}</span>
        </li>
        {% endfor %}
      </ul>
      <p class="order_box_total">Total: ${{ cart.get_total_price }}</p>
    </div>
  </div>

</section>
<script>

  const thePublishableKey = '{{pub_key|safe}}'
</script>
{% endblock %}