mysite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post_category/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<slug:post>/<int:year>/<int:month>/<int:day>', views.post_detail, name='post_detail'),
    path('categories/<slug:tag_slug>/', views.by_categories, name='by_categories'),
    path('all/', views.all_categories, name='all_categories'),
    path('feed/', LatestPostFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),

]

mysite/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from home_page.sitemaps import PostSitemap
from django.views.generic.base import TemplateView
import environ

env = environ.Env()
environ.Env.read_env()

sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path(env('SECRET_ADMIN_URL') + '/admin/', admin.site.urls),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('payments/', include('payments.urls', namespace='payments')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('store/', include('store.urls', namespace='store')),
    path('insightsTwo/',include('insightsTwo.urls', namespace='insightsTwo')),
    path('', include('home_page.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name="django.contrib.sitemaps.views.sitemap"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

]

mysite/store/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import FileExtensionValidator

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    class Meta:
        ordering=('name',)
        verbose_name_plural='categories'
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:product_list_by_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    pdf_file = models.FileField(upload_to='pdf_files/%Y/%m/%d', blank=True, validators=[FileExtensionValidator(["pdf"])])
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.id, self.slug])

mysite/store/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
import home_page

# Create your views here.

from .models import Category, Product
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(
        request,
        'store/products/list.html',
        {'category': category, 
        'categories':categories,
        'products':products}
        )

def product_detail(request, id, slug):
    product = get_object_or_404(
        Product,
        id=id,
        slug=slug,
        available=True
        )
    
    cart_product_form = CartAddProductForm()
    return render(request, 'store/products/detail.html', {'product': product, 'cart_product_form': cart_product_form})

mysite/templates/store/products/detail.html
{% extends 'layout.html' %}
{ load static }


{% block main %}
<section class="product_detail_section">
    <div class="container product_details_container">
        <div class="product_details_image">
            <img src="{{ product.image.url }}" alt="" class="curr_newsletter">
        </div>
        <div class="description_block">
            <h1 class="title_block">{% block title %}{{ product.name }}{% endblock %}</h1>
            <h2 class="category_block">{{ product.category }}</h2>
            <div class="product_description">
                <p>{{ product.description|linebreaks }}</p>
            </div>
            <div class="product_price">
                <p>${{ product.price }}</p>
                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                    <div hidden>{{ cart_product_form }}</div>
                    {% csrf_token %}
                    <input type="submit" id="cart_add" value="Add To Cart">
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

mysite/templates/store/products/list.html
{% extends 'layout.html' %}



{% block title %}
    {% if category %}{{ category.name }}{% else %}Library{% endif %}
{% endblock %}

{% block main %}
<section class="library_section">
    <h1 class="section_title_blue">Library</h1>
    <div class="container library_container">
        <aside id="sidebar">
            <h3>Categories</h3>
            <ul>
                <li {% if not category %} class="selected"{% endif %}>
                    <a href="{% url 'store:product_list' %}">All</a>
                </li>
                {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
                {% endfor %}
            </ul>
        </aside>
        <main id="main" class="product_list">
            {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{{ product.image.url }}" alt="">
                </a>
                <a class="product_name" href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                <br>
                    ${{ product.price }}
            </div>
            {% endfor %}
        </main>
    </div>
</section>
{% endblock %}